site_name: Documentation
docs_dir: docs
theme:
  name: material
  logo: assets/ozon-logo-white.png
  favicon: assets/images/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/git-alt
  custom_dir: material
  
  
  ## Navigation
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
  
  plugins:
    - search

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      #      primary: white
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: black)"
      scheme: slate
      #      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

repo_url: https://github.com/btechpt
repo_name: github.com/btechpt

nav:
  - Home: 'https://btech.id/ozon/'
  - Documentation:
      - Introduction: introduction.md
      - Architecture: architecture.md
      - Features: features.md
      #    - Deploy:
      #      - Pre-Requisites: prerequisites.md
      #      - Pre-Installation: pre-installation.md
      #      - Installation: installation.md
      - Usage:
          - Billing System:
              - Pre-Usages: preusages.md
              - Create price: price.md
              - Download invoice: invoice.md
              - Billing overview: billing-overview.md
              - Usages cost: cost.md
              - Company Profile: billing-settings.md
              - Notification center: notification.md
              - Email configuration: email_configuration.md
          - Centralized Region:
              - CRUD Region: ''
              - Move Region: ''
          - Theme Setting: ''
  - Repository: 'https://github.com/btechpt'
  - Demo: 'https://btech.id'

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

#extra:
#  analytics:
#    provider: google
#    property: G-MHL1SCTT37

copyright: Copyright &copy; 2023 - Ozon
